package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidateCheckList generated by hbm2java
 */
@Entity
@Table(name = "candidate_check_list", catalog = "ayant_trmsv2")
public class CandidateCheckList implements java.io.Serializable {

	private Integer id;
	private CheckListType checkListType;
	private String category;
	private Date checkListDate;
	private String checkListStatus;
	private String remarks;
	private int candidateId;
	private String mailDetails;
	private Integer mailCount;
	private Set<Documents> documentses = new HashSet<Documents>(0);

	public CandidateCheckList() {
	}

	public CandidateCheckList(int candidateId) {
		this.candidateId = candidateId;
	}

	public CandidateCheckList(CheckListType checkListType, String category, Date checkListDate, String checkListStatus,
			String remarks, int candidateId, String mailDetails, Integer mailCount, Set<Documents> documentses) {
		this.checkListType = checkListType;
		this.category = category;
		this.checkListDate = checkListDate;
		this.checkListStatus = checkListStatus;
		this.remarks = remarks;
		this.candidateId = candidateId;
		this.mailDetails = mailDetails;
		this.mailCount = mailCount;
		this.documentses = documentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "check_list_type_id")
	public CheckListType getCheckListType() {
		return this.checkListType;
	}

	public void setCheckListType(CheckListType checkListType) {
		this.checkListType = checkListType;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "check_list_date", length = 10)
	public Date getCheckListDate() {
		return this.checkListDate;
	}

	public void setCheckListDate(Date checkListDate) {
		this.checkListDate = checkListDate;
	}

	@Column(name = "check_list_status", length = 45)
	public String getCheckListStatus() {
		return this.checkListStatus;
	}

	public void setCheckListStatus(String checkListStatus) {
		this.checkListStatus = checkListStatus;
	}

	@Column(name = "remarks", length = 145)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "candidate_id", nullable = false)
	public int getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(int candidateId) {
		this.candidateId = candidateId;
	}

	@Column(name = "mail_details", length = 65535)
	public String getMailDetails() {
		return this.mailDetails;
	}

	public void setMailDetails(String mailDetails) {
		this.mailDetails = mailDetails;
	}

	@Column(name = "mail_count")
	public Integer getMailCount() {
		return this.mailCount;
	}

	public void setMailCount(Integer mailCount) {
		this.mailCount = mailCount;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "checklist_has_documents", catalog = "ayant_trmsv2", joinColumns = {
			@JoinColumn(name = "checklist_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "documents_id", nullable = false, updatable = false) })
	public Set<Documents> getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set<Documents> documentses) {
		this.documentses = documentses;
	}

}
