package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CandidateGroup generated by hbm2java
 */
@Entity
@Table(name = "candidate_group", catalog = "ayant_trmsv2")
public class CandidateGroup implements java.io.Serializable {

	private Integer groupId;
	private String groupDescription;
	private String groupName;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);

	public CandidateGroup() {
	}

	public CandidateGroup(String groupDescription, String groupName, Set<Candidate> candidates) {
		this.groupDescription = groupDescription;
		this.groupName = groupName;
		this.candidates = candidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "group_id", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_description", length = 145)
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@Column(name = "group_name", length = 45)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "candidateGroups")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

}
