package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ContactAddress generated by hbm2java
 */
@Entity
@Table(name = "contact_address", catalog = "ayant_trmsv2", uniqueConstraints = @UniqueConstraint(columnNames = "work_mobile"))
public class ContactAddress implements java.io.Serializable {

	private Integer contactId;
	private String address1;
	private String address2;
	private String addressType;
	private String alternateEmail;
	private String city;
	private String country;
	private String email;
	private String facebook;
	private String fax;
	private String homeMobile;
	private String homePhone;
	private String landmark;
	private String linkedin;
	private String msn;
	private Integer postalCode;
	private String remarks;
	private String skype;
	private String state;
	private String twitter;
	private String workMobile;
	private String workPhone;
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Trainer> trainers = new HashSet<Trainer>(0);
	private Set<Candidate> candidates = new HashSet<Candidate>(0);

	public ContactAddress() {
	}

	public ContactAddress(String address1, String address2, String addressType, String alternateEmail, String city,
			String country, String email, String facebook, String fax, String homeMobile, String homePhone,
			String landmark, String linkedin, String msn, Integer postalCode, String remarks, String skype,
			String state, String twitter, String workMobile, String workPhone, Set<Employee> employees,
			Set<Trainer> trainers, Set<Candidate> candidates) {
		this.address1 = address1;
		this.address2 = address2;
		this.addressType = addressType;
		this.alternateEmail = alternateEmail;
		this.city = city;
		this.country = country;
		this.email = email;
		this.facebook = facebook;
		this.fax = fax;
		this.homeMobile = homeMobile;
		this.homePhone = homePhone;
		this.landmark = landmark;
		this.linkedin = linkedin;
		this.msn = msn;
		this.postalCode = postalCode;
		this.remarks = remarks;
		this.skype = skype;
		this.state = state;
		this.twitter = twitter;
		this.workMobile = workMobile;
		this.workPhone = workPhone;
		this.employees = employees;
		this.trainers = trainers;
		this.candidates = candidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "contact_id", unique = true, nullable = false)
	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	@Column(name = "address1", length = 145)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 145)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address_type", length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "alternate_email", length = 60)
	public String getAlternateEmail() {
		return this.alternateEmail;
	}

	public void setAlternateEmail(String alternateEmail) {
		this.alternateEmail = alternateEmail;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "email", length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "facebook", length = 100)
	public String getFacebook() {
		return this.facebook;
	}

	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "home_mobile", length = 20)
	public String getHomeMobile() {
		return this.homeMobile;
	}

	public void setHomeMobile(String homeMobile) {
		this.homeMobile = homeMobile;
	}

	@Column(name = "home_phone", length = 20)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "landmark", length = 145)
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Column(name = "linkedin", length = 100)
	public String getLinkedin() {
		return this.linkedin;
	}

	public void setLinkedin(String linkedin) {
		this.linkedin = linkedin;
	}

	@Column(name = "msn", length = 45)
	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	@Column(name = "postal_code")
	public Integer getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "remarks", length = 145)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "skype", length = 45)
	public String getSkype() {
		return this.skype;
	}

	public void setSkype(String skype) {
		this.skype = skype;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "twitter", length = 100)
	public String getTwitter() {
		return this.twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

	@Column(name = "work_mobile", unique = true, length = 20)
	public String getWorkMobile() {
		return this.workMobile;
	}

	public void setWorkMobile(String workMobile) {
		this.workMobile = workMobile;
	}

	@Column(name = "work_phone", length = 20)
	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactAddress")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactAddress")
	public Set<Trainer> getTrainers() {
		return this.trainers;
	}

	public void setTrainers(Set<Trainer> trainers) {
		this.trainers = trainers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactAddress")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

}
