package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FollowUp generated by hbm2java
 */
@Entity
@Table(name = "follow_up", catalog = "ayant_trmsv2")
public class FollowUp implements java.io.Serializable {

	private Integer followUpId;
	private Candidate candidate;
	private Employee employee;
	private Date followUpDate;
	private String followUpRemarks;
	private String followUpType;
	private Date nextFollowUpDate;

	public FollowUp() {
	}

	public FollowUp(Candidate candidate, Employee employee) {
		this.candidate = candidate;
		this.employee = employee;
	}

	public FollowUp(Candidate candidate, Employee employee, Date followUpDate, String followUpRemarks,
			String followUpType, Date nextFollowUpDate) {
		this.candidate = candidate;
		this.employee = employee;
		this.followUpDate = followUpDate;
		this.followUpRemarks = followUpRemarks;
		this.followUpType = followUpType;
		this.nextFollowUpDate = nextFollowUpDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "follow_up_id", unique = true, nullable = false)
	public Integer getFollowUpId() {
		return this.followUpId;
	}

	public void setFollowUpId(Integer followUpId) {
		this.followUpId = followUpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "candidate_id", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "next_follow_up_emp_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "follow_up_date", length = 19)
	public Date getFollowUpDate() {
		return this.followUpDate;
	}

	public void setFollowUpDate(Date followUpDate) {
		this.followUpDate = followUpDate;
	}

	@Column(name = "follow_up_remarks", length = 245)
	public String getFollowUpRemarks() {
		return this.followUpRemarks;
	}

	public void setFollowUpRemarks(String followUpRemarks) {
		this.followUpRemarks = followUpRemarks;
	}

	@Column(name = "follow_up_type", length = 45)
	public String getFollowUpType() {
		return this.followUpType;
	}

	public void setFollowUpType(String followUpType) {
		this.followUpType = followUpType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "next_follow_up_date", length = 19)
	public Date getNextFollowUpDate() {
		return this.nextFollowUpDate;
	}

	public void setNextFollowUpDate(Date nextFollowUpDate) {
		this.nextFollowUpDate = nextFollowUpDate;
	}

}
