package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaskHasDocumentsId generated by hbm2java
 */
@Embeddable
public class TaskHasDocumentsId implements java.io.Serializable {

	private int taskId;
	private int documentsId;

	public TaskHasDocumentsId() {
	}

	public TaskHasDocumentsId(int taskId, int documentsId) {
		this.taskId = taskId;
		this.documentsId = documentsId;
	}

	@Column(name = "task_id", nullable = false)
	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	@Column(name = "documents_id", nullable = false)
	public int getDocumentsId() {
		return this.documentsId;
	}

	public void setDocumentsId(int documentsId) {
		this.documentsId = documentsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskHasDocumentsId))
			return false;
		TaskHasDocumentsId castOther = (TaskHasDocumentsId) other;

		return (this.getTaskId() == castOther.getTaskId()) && (this.getDocumentsId() == castOther.getDocumentsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTaskId();
		result = 37 * result + this.getDocumentsId();
		return result;
	}

}
