package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TaskHasDocuments generated by hbm2java
 */
@Entity
@Table(name = "task_has_documents", catalog = "ayant_trmsv2")
public class TaskHasDocuments implements java.io.Serializable {

	private TaskHasDocumentsId id;

	public TaskHasDocuments() {
	}

	public TaskHasDocuments(TaskHasDocumentsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "taskId", column = @Column(name = "task_id", nullable = false)),
			@AttributeOverride(name = "documentsId", column = @Column(name = "documents_id", nullable = false)) })
	public TaskHasDocumentsId getId() {
		return this.id;
	}

	public void setId(TaskHasDocumentsId id) {
		this.id = id;
	}

}
