package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaskRole generated by hbm2java
 */
@Entity
@Table(name = "task_role", catalog = "ayant_trmsv2")
public class TaskRole implements java.io.Serializable {

	private Integer id;
	private String description;
	private String role;
	private Set<EmployeeHasTask> employeeHasTasks = new HashSet<EmployeeHasTask>(0);

	public TaskRole() {
	}

	public TaskRole(String role) {
		this.role = role;
	}

	public TaskRole(String description, String role, Set<EmployeeHasTask> employeeHasTasks) {
		this.description = description;
		this.role = role;
		this.employeeHasTasks = employeeHasTasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "role", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taskRole")
	public Set<EmployeeHasTask> getEmployeeHasTasks() {
		return this.employeeHasTasks;
	}

	public void setEmployeeHasTasks(Set<EmployeeHasTask> employeeHasTasks) {
		this.employeeHasTasks = employeeHasTasks;
	}

}
