package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrainerInvoice generated by hbm2java
 */
@Entity
@Table(name = "trainer_invoice", catalog = "ayant_trmsv2")
public class TrainerInvoice implements java.io.Serializable {

	private Integer trainerInvoiceId;
	private CandidateCourse candidateCourse;
	private ProgrammeSchedule programmeSchedule;
	private String payMonth;
	private BigDecimal amount;
	private Integer noOfStudent;
	private Date invoiceDate;
	private Integer noOfDays;
	private String trainerPanNo;
	private String trainerBankName;
	private String bankAccount;
	private String bankIfsc;
	private String invoiceDescription;
	private String payYear;
	private Integer trainerId;

	public TrainerInvoice() {
	}

	public TrainerInvoice(CandidateCourse candidateCourse, ProgrammeSchedule programmeSchedule, String payMonth,
			BigDecimal amount, Integer noOfStudent, Date invoiceDate, Integer noOfDays, String trainerPanNo,
			String trainerBankName, String bankAccount, String bankIfsc, String invoiceDescription, String payYear,
			Integer trainerId) {
		this.candidateCourse = candidateCourse;
		this.programmeSchedule = programmeSchedule;
		this.payMonth = payMonth;
		this.amount = amount;
		this.noOfStudent = noOfStudent;
		this.invoiceDate = invoiceDate;
		this.noOfDays = noOfDays;
		this.trainerPanNo = trainerPanNo;
		this.trainerBankName = trainerBankName;
		this.bankAccount = bankAccount;
		this.bankIfsc = bankIfsc;
		this.invoiceDescription = invoiceDescription;
		this.payYear = payYear;
		this.trainerId = trainerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "trainer_invoice_id", unique = true, nullable = false)
	public Integer getTrainerInvoiceId() {
		return this.trainerInvoiceId;
	}

	public void setTrainerInvoiceId(Integer trainerInvoiceId) {
		this.trainerInvoiceId = trainerInvoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id")
	public CandidateCourse getCandidateCourse() {
		return this.candidateCourse;
	}

	public void setCandidateCourse(CandidateCourse candidateCourse) {
		this.candidateCourse = candidateCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "batch_id")
	public ProgrammeSchedule getProgrammeSchedule() {
		return this.programmeSchedule;
	}

	public void setProgrammeSchedule(ProgrammeSchedule programmeSchedule) {
		this.programmeSchedule = programmeSchedule;
	}

	@Column(name = "pay_month", length = 45)
	public String getPayMonth() {
		return this.payMonth;
	}

	public void setPayMonth(String payMonth) {
		this.payMonth = payMonth;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "no_of_student")
	public Integer getNoOfStudent() {
		return this.noOfStudent;
	}

	public void setNoOfStudent(Integer noOfStudent) {
		this.noOfStudent = noOfStudent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "invoice_date", length = 10)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Column(name = "no_of_days")
	public Integer getNoOfDays() {
		return this.noOfDays;
	}

	public void setNoOfDays(Integer noOfDays) {
		this.noOfDays = noOfDays;
	}

	@Column(name = "trainer_pan_no", length = 200)
	public String getTrainerPanNo() {
		return this.trainerPanNo;
	}

	public void setTrainerPanNo(String trainerPanNo) {
		this.trainerPanNo = trainerPanNo;
	}

	@Column(name = "trainer_bank_name", length = 200)
	public String getTrainerBankName() {
		return this.trainerBankName;
	}

	public void setTrainerBankName(String trainerBankName) {
		this.trainerBankName = trainerBankName;
	}

	@Column(name = "bank_account", length = 200)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "bank_ifsc", length = 100)
	public String getBankIfsc() {
		return this.bankIfsc;
	}

	public void setBankIfsc(String bankIfsc) {
		this.bankIfsc = bankIfsc;
	}

	@Column(name = "invoice_description", length = 65535)
	public String getInvoiceDescription() {
		return this.invoiceDescription;
	}

	public void setInvoiceDescription(String invoiceDescription) {
		this.invoiceDescription = invoiceDescription;
	}

	@Column(name = "pay_year", length = 45)
	public String getPayYear() {
		return this.payYear;
	}

	public void setPayYear(String payYear) {
		this.payYear = payYear;
	}

	@Column(name = "trainer_id")
	public Integer getTrainerId() {
		return this.trainerId;
	}

	public void setTrainerId(Integer trainerId) {
		this.trainerId = trainerId;
	}

}
