package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trainer generated by hbm2java
 */
@Entity
@Table(name = "trainer", catalog = "ayant_trmsv2")
public class Trainer implements java.io.Serializable {

	private Integer id;
	private CandidateCourse candidateCourse;
	private ContactAddress contactAddress;
	private String trainerName;
	private String trainerBankName;
	private String bankAccount;
	private String bankIfsc;
	private String accountType;
	private String modeOfPayment;
	private Boolean active;
	private BigDecimal salary;
	private String pancardNo;
	private String bankBranchName;
	private Set<ProgrammeSchedule> programmeSchedules = new HashSet<ProgrammeSchedule>(0);

	public Trainer() {
	}

	public Trainer(CandidateCourse candidateCourse, ContactAddress contactAddress) {
		this.candidateCourse = candidateCourse;
		this.contactAddress = contactAddress;
	}

	public Trainer(CandidateCourse candidateCourse, ContactAddress contactAddress, String trainerName,
			String trainerBankName, String bankAccount, String bankIfsc, String accountType, String modeOfPayment,
			Boolean active, BigDecimal salary, String pancardNo, String bankBranchName,
			Set<ProgrammeSchedule> programmeSchedules) {
		this.candidateCourse = candidateCourse;
		this.contactAddress = contactAddress;
		this.trainerName = trainerName;
		this.trainerBankName = trainerBankName;
		this.bankAccount = bankAccount;
		this.bankIfsc = bankIfsc;
		this.accountType = accountType;
		this.modeOfPayment = modeOfPayment;
		this.active = active;
		this.salary = salary;
		this.pancardNo = pancardNo;
		this.bankBranchName = bankBranchName;
		this.programmeSchedules = programmeSchedules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public CandidateCourse getCandidateCourse() {
		return this.candidateCourse;
	}

	public void setCandidateCourse(CandidateCourse candidateCourse) {
		this.candidateCourse = candidateCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_address_id", nullable = false)
	public ContactAddress getContactAddress() {
		return this.contactAddress;
	}

	public void setContactAddress(ContactAddress contactAddress) {
		this.contactAddress = contactAddress;
	}

	@Column(name = "trainer_name", length = 100)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Column(name = "trainer_bank_name", length = 200)
	public String getTrainerBankName() {
		return this.trainerBankName;
	}

	public void setTrainerBankName(String trainerBankName) {
		this.trainerBankName = trainerBankName;
	}

	@Column(name = "bank_account", length = 200)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "bank_ifsc", length = 200)
	public String getBankIfsc() {
		return this.bankIfsc;
	}

	public void setBankIfsc(String bankIfsc) {
		this.bankIfsc = bankIfsc;
	}

	@Column(name = "account_type", length = 100)
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "mode_of_payment", length = 50)
	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "salary", precision = 10)
	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	@Column(name = "pancard_no", length = 45)
	public String getPancardNo() {
		return this.pancardNo;
	}

	public void setPancardNo(String pancardNo) {
		this.pancardNo = pancardNo;
	}

	@Column(name = "bank_branch_name", length = 45)
	public String getBankBranchName() {
		return this.bankBranchName;
	}

	public void setBankBranchName(String bankBranchName) {
		this.bankBranchName = bankBranchName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trainer")
	public Set<ProgrammeSchedule> getProgrammeSchedules() {
		return this.programmeSchedules;
	}

	public void setProgrammeSchedules(Set<ProgrammeSchedule> programmeSchedules) {
		this.programmeSchedules = programmeSchedules;
	}

}
