package com.ayantsoft.vitalglobal.pojo;
// Generated 21 Dec, 2017 4:58:49 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "ayant_trmsv2", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class UserProfile implements java.io.Serializable {

	private Integer userId;
	private Boolean enabled;
	private String officeEmail;
	private String officeEmailPwd;
	private String password;
	private String username;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public UserProfile() {
	}

	public UserProfile(Boolean enabled, String officeEmail, String officeEmailPwd, String password, String username,
			Set<Candidate> candidates, Set<Role> roles, Set<Employee> employees) {
		this.enabled = enabled;
		this.officeEmail = officeEmail;
		this.officeEmailPwd = officeEmailPwd;
		this.password = password;
		this.username = username;
		this.candidates = candidates;
		this.roles = roles;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "office_email", length = 45)
	public String getOfficeEmail() {
		return this.officeEmail;
	}

	public void setOfficeEmail(String officeEmail) {
		this.officeEmail = officeEmail;
	}

	@Column(name = "office_email_pwd", length = 45)
	public String getOfficeEmailPwd() {
		return this.officeEmailPwd;
	}

	public void setOfficeEmailPwd(String officeEmailPwd) {
		this.officeEmailPwd = officeEmailPwd;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_has_role", catalog = "ayant_trmsv2", joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_type", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
